name: Sync Fork With forked repo
on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT_TOKEN}}
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://minjeong9919:${{ secrets.PAT_TOKEN }}@github.com/minjeong9919/BrainPix-front
          git config user.name minejeong9919
          git config user.email "minjeong9919@github.com"

      - name: Push changes to Forked-reop
        run: |
          git push -f https://github.com/BrainPix/BrainPix-front develop

      - name: Clean up
        run: |
          git remote remove forked-repo
